# Generated by Django 4.0.2 on 2022-03-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_commentlike_postlike_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='reader',
            new_name='viewer',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tag_name',
        ),
    ]
