# Generated by Django 4.0.2 on 2022-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tags', through='postings.TagList', to='postings.Tag'),
        ),
    ]
