# Generated by Django 4.0.2 on 2022-02-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('profile_image', models.URLField(max_length=300, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('kakao_id', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
